name: CI
on: push
jobs:
  matrixJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install --global zx
    - id: getMatrix
      run: echo "::set-output name=matrixData::$(zx ./.github/workflows/getMatrixData.mjs)"
    - run: echo ${{ steps.getMatrix.outputs.matrixData }}
    outputs:
      matrix: ${{ steps.getMatrix.outputs.matrixData }}

  test:
    needs: matrixJob
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrixJob.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
