name: CI
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm i -g zx
    - id: set-matrix
      run: echo "::set-output name=matrix::$(zx ./.github/workflows/getMatrix.mjs)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
