name: CI
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i -g zx
    - id: getMatrixData
      run: echo "::set-output name=matrixData::$(zx ./.github/workflows/getMatrixData.mjs)"
    - run: echo ${{ steps.getMatrixData.outputs.matrixData }}
    outputs:
      matrix: ${{ steps.getMatrixData.outputs.matrixData }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrixData)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
